### ISSUE TITLE
alicloud_db_account multiple issues

### ISSUE THREAD

**Issue by firasnajjar** [alibaba/terraform-provider#768]
I'm using a domestic account in the Frankfurt region.

Run the following terraform:

```
provider "alicloud" {
  access_key = "your access key"
  secret_key = "your secret key"
  region = "eu-central-1"
}

resource "alicloud_vpc" "vpc" {
  name       = "test_vpc4"
  cidr_block = "10.0.0.0/8"
}

resource "alicloud_vswitch" "vsw" {
  vpc_id            = "${alicloud_vpc.vpc.id}"
  cidr_block        = "10.0.0.0/24"
  availability_zone = "eu-central-1a"
  name              = "rds_subnet"
}

resource "alicloud_db_instance" "cf_postgres" {
  engine            = "PostgreSQL"
  engine_version    = "10.0"
  instance_type     = "pg.n1.micro.1"
  instance_storage  = "20"
  instance_name     = "test_postgres_batata"
  zone_id           = "eu-central-1a"
  vswitch_id        = "${alicloud_vswitch.vsw.id}"
  security_ips      = ["0.0.0.0/0"]
}

resource "alicloud_db_account" "cf_postgres_account" {
  instance_id       = "${alicloud_db_instance.cf_postgres.id}"
  name              = "aabb"
  password          = "your password"
  description       = "The credetnials used to access the RDS database"
}
```

Running terraform apply succeeds. After running it, if you run terraform plan you will get the following:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ alicloud_db_account.cf_postgres_account
      type: "Super" => "Normal"


Plan: 0 to add, 1 to change, 0 to destroy.
```

According to your documentation here:

https://www.terraform.io/docs/providers/alicloud/r/db_account.html

The "type" field is valid only for MySQL. Why does it appear here then?

Running terraform apply again won't change the type. Running plan will always show changes!

**Comment by firasnajjar** [comment]
In addition, trying to run terraform destroy on the code above leads to the following error:
```
Error: Error applying plan:

1 error(s) occurred:

* alicloud_db_account.cf_postgres_account (destroy): 1 error(s) occurred:

* alicloud_db_account.cf_postgres_account: Delete database account got an error: &errors.ServerError{httpStatus:403, requestId:"A12CAB1D-2A40-4CFB-9FD6-F3BBC206DDF3", hostId:"rds.eu-central-1.aliyuncs.com", errorCode:"InstanceEngineType.NotSupport", recommend:"", message:"The instance engine and type does not support operations.", comment:""
```

Trying to run destroy multiple times doesn't help either.

After that I tried to delete the account manually in the web console. There is no option to do that there. So I released the whole RDS instance from the web console. It worked. I assumed it should also remove the account but it doesn't seem to be the case since if I run terraform destroy now, terraform execution plan shows the following:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - alicloud_db_account.cf_postgres_account

  - alicloud_vpc.vpc

  - alicloud_vswitch.vsw


Plan: 0 to add, 0 to change, 3 to destroy.
```

Which means that terraform understood that the instance was released but it didn't understand that the account was too!

So terraform destroy failed again with the same error on the account and an additional error on the VPC:
```
Error: Error applying plan:

2 error(s) occurred:

* alicloud_db_account.cf_postgres_account (destroy): 1 error(s) occurred:

* alicloud_db_account.cf_postgres_account: Delete database account got an error: &errors.ServerError{httpStatus:400, requestId:"A2124C1C-20A6-4506-9928-8D3A81C77229", hostId:"rds.eu-central-1.aliyuncs.com", errorCode:"InvalidDBInstanceId.NotFound", recommend:"", message:"DBInstanceIdentifier does not refer to an existing DB instance.", comment:""}.
* alicloud_vpc.vpc (destroy): 1 error(s) occurred:

* alicloud_vpc.vpc: Delete VPC timeout and got an error: &errors.ServerError{httpStatus:400, requestId:"E317ABF6-9326-4203-860A-420F7C72F890", hostId:"vpc.eu-central-1.aliyuncs.com", errorCode:"DependencyViolation.SecurityGroup", recommend:"", message:"Specified object has dependent resources SecurityGroup.", comment:""}.
```

Since I assume that the account was deleted with the database instance, I remove it from state using:

```
terraform state rm alicloud_db_account.cf_postgres_account
```

I ran terraform destroy again, and now it fails on the security group error although there are no security groups in the VPC! I'm stuck with this VPC and I cannot delete it at all even from the web console!

**Comment by bilonic** [comment]
I have the same issue with **alicloud_db_account**

**Comment by xiaozhu36** [comment]
HI @firasnajjar At present, the `alicloud_db_account` only supports MySQL 5.5/5.6. Please check it.

Does the another issue `Delete VPC timeout` still exist.

**Comment by xiaozhu36** [comment]
Closed by no reply
